### ISSUE TITLE
replace wget with archive

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-minecraft#10]
We've this in [plugin.pp](https://github.com/voxpupuli/puppet-minecraft/commit/13d98b1ecc61b2bfe7677d10c8baae7681db0925): 
```puppet
  wget::fetch { $plugin_name:
    source      => $source,
    destination => "${minecraft::install_dir}/plugins/${plugin_name}.jar",
    user        => $minecraft::user,
    notify      => Service['minecraft'],
    require     => File["${minecraft::install_dir}/plugins"],
  }
```

we should replace it with archive. This is based on https://github.com/voxpupuli/puppet-minecraft/pull/9#discussion_r65820444

**Comment by bbriggs** [comment]
I'll take this one.

**Comment by bbriggs** [comment]
Am I missing something? Are there actually no tests for this module or are they socked away in some weird place, like Modulefile/metadata.json?

**Comment by bastelfreak** [comment]
no spec tests yet, would be cool if you could and some at least for your changes.

**Comment by bbriggs** [comment]
Will do

**Comment by bbriggs** [comment]
Do this for source.pp as well?

**Comment by alexjfisher** [comment]
Fixed in https://github.com/voxpupuli/puppet-minecraft/pull/13
